name: yandex-parser
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.2.0
  - pandas=1.4.3
  - pyarrow=9.0.0
  - numpy=1.23.2
  - tqdm=4.64.1
  - pip=21.2.4
  - pip:
      - hydra_submitit_launcher==1.2.0
