dataset_directory: data
output_directory: data
row_group_size: 65536 # Number of queries to encode into a single parquet row_block

relevance_dataset:
  _target_: src.data.YandexRelevanceDataset
  path: ${dataset_directory}/Trainq.txt

click_dataset:
  _target_: src.data.YandexClickDataset
  path: ${dataset_directory}/YandexClicks.txt
  filter_queries_without_relevance: True

document_encoder: # Optionally encode query, document combinations using unique ids. Turn off by setting to `null`
  _target_: src.util.LabelEncoder
