dataset_directory: data
output_directory: data

relevance_dataset:
  _target_: src.data.YandexRelevanceDataset
  path: ${dataset_directory}/Trainq.txt

click_dataset:
  _target_: src.data.YandexClickDataset
  path: ${dataset_directory}/YandexClicks.txt
  filter_queries_without_relevance: True
